version: '3.4'
services:
  payment:
    build: ./payment-service
    volumes:
      - ./payment-service:/data
    ports:
      - "9002:9002"
  orders:
    build: ./orders-service
    volumes:
      - ./orders-service:/data
    ports:
      - "9000:9000"
  warehouse:
    build: ./warehouse-service
    volumes:
      - ./warehouse-service:/data
    ports:
      - "9001:9001"