version: '3.4'
services:
  eureka:
    build: ./eureka-server
    ports:
      - "8761:8761"
  payment:
    build: ./payment-service
    volumes:
      - ./payment-service:/data
    ports:
      - "9002:9002"
  orders:
    build: ./orders-service
    volumes:
      - ./orders-service:/data
    ports:
      - "9000:9000"
    restart: on-failure
    depends_on:
      - rabbitmq
  warehouse:
    build: ./warehouse-service
    volumes:
      - ./warehouse-service:/data
    ports:
      - "9001:9001"
    restart: on-failure
    depends_on:
      - orders
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4368:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
  api-gateway:
    build: ./api-gateway
    ports:
      - "8111:8111"
